haircut/urls.py
from django.urls import path
from . import views 

app_name = 'haircut'

urlpatterns = [
   path("", views.home_page, name= 'home_page'),
]

salon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [ path("",include('haircut.urls')),
    path('admin/', admin.site.urls),
]

haircut/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
     comment = models.CharField(max_length=180, null=True, blank=True)
     user = models.CharField(max_length=180, null=True, blank=True)

haircut/views.py
from django.shortcuts import render

# Create your views here.
def home_page(request):
  
  if request.method == 'POST':
  	 time = request.POST.get('time')
  	 barber = request.POST.get("barber_name")

  	 return render(request, 'haircut/home_page.html', {context}
  return render(request,'haircut/home_page.html')

haircut/templates/haircut/home_page.html
<!DOCTYPE html>
<html>
<head>
 <title>Amazing Amy’s Barbershop</title>
</head>
<body>
    <h1> Amazing Amy’s Barbershop</h1>
    <p>A Fresh Cut You And Your Family!</p>
     
    <p>Kevin</p>
    <img src="http://www.oldtownbarberclub.com/wp-content/uploads/2015/01/slide01.jpg">

    <p>Jay</p>
    <img src="http://americanbeautycollege.com/wp-content/uploads/2014/09/barber.png">

    <p>Helen</p>
    <img src="https://tse4-mm.cn.bing.net/th?id=OIP.w3WLDEtRv93JHpfrpdAQKAHaFd&pid=Api">

    <h1>Place Your Order</h1>
    <form action="{% url 'haircut:home_page' %} " method="POST">
        {% csrf_token %}"
        <input type="text" name="time" placeholder = "enter the time"><br>
        <textarea placeholder="Text the barber you want" name="barber"></textarea><br>
        <input type="submit" value="submit">
    </form>
    <h1>Your Order</h1>
    <p>Time: {{time}}</p>
    <p>Barber: {{barber}}</p>

</body>
</html>
 